AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Relational Database Service (RDS) Instance Template
Resources:
  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - <MySecurityGroup>
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: playground-db
      Engine: MySQL
      MasterUsername: Admin
      MasterUserPassword: CloudAcademy123!
